演習プログラム１

In [2]:
# Numpyモジュールをnpという名前でimport
import numpy as np

In [3]:
# 2行2列の2次元Array作成
a1 = np.array([[1,2],[3,4]])

a1

array([[1, 2],
       [3, 4]])

In [4]:
# a1+a1（要素ごとの和）
# 1+1, 2+2, 3+3, 4+4
a1+a1

array([[2, 4],
       [6, 8]])

In [5]:
# a1*a1（要素ごとの積）
# 1*1, 2*2, 3*3, 4*4
a1*a1

array([[ 1,  4],
       [ 9, 16]])

In [6]:
# 2をArrayの各要素で割る
2 / a1

array([[2.        , 1.        ],
       [0.66666667, 0.5       ]])

In [12]:
arr1 = np.array([[1,2]])

arr1

array([[1, 2]])

In [13]:
arr2 = np.array([3,4])

arr2

array([3, 4])

In [17]:
#ベクトルの内積
# 1*3+2*4
np.dot(arr1,arr2)

array([11])

In [ ]:
arr1 = np.array([[2,1],[1,0]])

arr1

array([[2, 1],
       [1, 0]])

In [ ]:
arr2 = np.array([[1,-1],[0,-2]])

arr2

array([[ 1, -1],
       [ 0, -2]])

In [16]:
# 2行2列の行列の内積
np.dot(arr1,arr2)

array([11])

In [ ]:
arr1 = np.array([[0,1],[2,3],[4,5]])

arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr2 = np.array([[0,1,2],[4,5,6]])

arr2

array([[0, 1, 2],
       [4, 5, 6]])

In [ ]:
#3行2列×2行3列
np.dot(arr1,arr2)

array([[ 4,  5,  6],
       [12, 17, 22],
       [20, 29, 38]])