In [2]:
# Numpyモジュールをnpという名前でimport
import numpy as np

In [3]:
# 2行4列の2次元Array作成
a1 = np.array([[1,2,3,4],[5,6,7,8]])

In [4]:
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# a1*a1（arry * arryの乗算）
a1*a1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [6]:
# a1 - a1（array - arrayの減算）
a1-a1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
# 2をArrayの各要素で割る
2 / a1

array([[2.        , 1.        , 0.66666667, 0.5       ],
       [0.4       , 0.33333333, 0.28571429, 0.25      ]])