演習プログラム１

In [2]:
# Numpyライブラリをnpという名前でimport
import numpy as np

# Pythonのlistを1つ作成
list1 = [1,2,3,4]

# Numpyのarray関数にlist1を格納して作成
array1 = np.array(list1)

In [3]:
# array1を表示すると1次元numpy配列のlistの中身が格納されている
array1

array([1, 2, 3, 4])

演習プログラム２

In [4]:
# 2次元numpy配列を生成
array = np.array([[1, 2, 3], [4, 5, 6]])

array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 別のlist2を作成
list2 = [5,6,7,8]

# list1とlist2を含んだlistsを作成
lists = [list1,list2]   #[[1,2,3,4], [5,6,7,8]]

# listsを、Numpyのarrayに格納すると2行4列の2次元配列arrayができる
array2 = np.array(lists)

# array2を表示すると2次元配列のlist1とlist2の中身が格納されてい
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

補足プログラム

In [6]:
# Numpyのshapeメソッド（サイズを確認）
array2.shape    #2行4列の2次元配列

(2, 4)

In [7]:
# Numpyのdtypeメソッド（arrayのデータ型を確認）
#int32は符号付32ビット整数型
array2.dtype

dtype('int32')

In [8]:
#numpyのデータ型の指定
#int64は符号付64ビット整数型
array3 = np.array(lists, dtype='int64')

array3.dtype

dtype('int64')

In [9]:
# すべての要素が0の1次元array生成
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
# 名前を付けて格納
zeros_array = np.zeros(5)

In [11]:
# データ型を確認
zeros_array.dtype

dtype('float64')

In [12]:
#すべての要素が4行5列の2次元Array生成
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# arange関数 ・・・0から()内の数値の1つ前までの整数でArray生成
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# 初期値,最終値,ステップを指定
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])